version: '3.8'

volumes:
  data:
  uploads:

networks:
  backend:

services:
  # POSTGRES
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - backend

  # BACKEND (Django)
  back:
    image: python:3.9 
    container_name: backend
    working_dir: /app
    command: sh -c "pip install -r requirements.txt
                    && python manage.py migrate
                    && daphne -b 0.0.0.0 -p 4000 Transcendance_Back.asgi:application"
    volumes:
      - ./Transcendance_Back:/app 
    ports:
      - "4000:4000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=Transcendance_Back.settings
      - DB_HOST=postgres 
    depends_on:
      - postgres 
    networks:
      - backend 

  # NGINX
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - back
      - postgres
    networks:
      - backend