version: '3.8'

services:

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./Transcendance_Back
    restart: always
    # env_file:
    #   - /.env
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_database_name

volumes:
  postgres_data:
